% This is an autogenerated sample test for file rockPpaerScissors
classdef testrockPaperScissors < matlab.unittest.TestCase
    methods (Test)
        function test_rockPpaerScissors(testCase)
            % Specify the input(s) of rockPpaerScissors
            player1 = "rock";
            player2 = "scissors";

            % Exercise the function rockPpaerScissors
            actualOutput_result = rockPaperScissors(player1,player2);

            % Specify the expected output(s) of rockPpaerScissors
            expectedOutput_result = "Player 1 wins";

            testCase.verifyEqual(actualOutput_result, expectedOutput_result);
        end
    end
end